linters:
  enable-all: true
  disable:
    - gci
    - nlreturn
    - goerr113
    - exhaustivestruct
    - lll
    - typecheck
    - goimports
    - dupl
    - interfacer
    - wsl
    - gochecknoglobals
